using LifeOS.Companion.Core.Models;using LifeOS.Companion.Core.Pairing;using LifeOS.Companion.Core.Services;using LifeOS.Companion.Core.Storage;using LifeOS.Companion.Security;
namespace LifeOS.Companion.Views;
public sealed class GlanceContentPage:ContentPage
{
 readonly ICompanionStore _store;readonly PairingCredentialStore _credentials;readonly CompanionTransferClient _client;readonly VerticalStackLayout _items=new();readonly Label _status=new();
 public GlanceContentPage(ICompanionStore store,PairingCredentialStore credentials,CompanionTransferClient client){_store=store;_credentials=credentials;_client=client;Title="Glance";var refresh=new Button{Text="Refresh explicitly"};SemanticProperties.SetDescription(refresh,"Refresh read-only glance data from paired Desktop");refresh.Clicked+=async(_,__)=>await RefreshFromDesktop();Content=new ScrollView{Content=new VerticalStackLayout{Padding=16,Spacing=12,Children={new Label{Text="Read-only glance",FontSize=26,FontAttributes=FontAttributes.Bold},new Label{Text="Agenda and Waiting-on / Work summaries. This screen cannot edit trusted Desktop records."},_status,refresh,_items}}};}
 protected override async void OnAppearing(){base.OnAppearing();await Render(await _store.GetGlanceAsync(),false);}
 async Task RefreshFromDesktop(){var c=await _credentials.LoadAsync();if(c is null){_status.Text="Not paired. Cached data remains available.";return;}try{var snapshots=await _client.GetGlanceAsync(c);foreach(var s in snapshots)await _store.SaveGlanceAsync(s);await Render(snapshots,false);}catch(Exception ex){await Render(await _store.GetGlanceAsync(),true);_status.Text="Desktop unavailable. Showing cached data. "+ex.Message;}}
 async Task Render(IReadOnlyList<GlanceSnapshot> snapshots,bool offline){_items.Children.Clear();if(snapshots.Count==0){_status.Text="No cached glance data. Refresh manually while Desktop receiving is enabled.";return;}foreach(var s in snapshots){var stale=offline||s.IsStale(DateTimeOffset.UtcNow);var stack=new VerticalStackLayout{Spacing=6};stack.Add(new Label{Text=$"{s.Kind} — {(stale?"STALE / OFFLINE":"CURRENT")}",FontAttributes=FontAttributes.Bold});stack.Add(new Label{Text=$"Source: {s.Source} · Last updated: {s.UpdatedAtUtc.LocalDateTime:g} · Read-only"});foreach(var i in s.Items)stack.Add(new Label{Text=$"• {i.Heading}{(string.IsNullOrWhiteSpace(i.Detail)?"":" — "+i.Detail)}"});_items.Add(new Border{Padding=12,Content=stack});}_status.Text=offline?"Offline/unavailable. No queued capture was sent.":"Read-only glance loaded.";await Task.CompletedTask;}
}
