using LifeOS.Core.ConfigurationReadiness;
using LifeOS.Core.Forms;

namespace LifeOS.Core.ProviderAdapters;

public enum ProviderFamily { Generic = 0, Google = 10, Microsoft = 20, OpenAi = 30 }
[Flags] public enum ProviderCapability { None = 0, CalendarRead = 1, EmailRead = 2, FileRead = 4, DraftProposal = 8, ProviderWrite = 16 }
public enum ProviderAdapterState { Planned = 0, AvailableForCredentialedTest = 10, Blocked = 20, Retired = 30 }
public sealed record ProviderAdapterDraft(string? Name, ProviderFamily Family, string? Owner, ConfigurationEnvironment Environment, ProviderCapability Capabilities, string? CredentialReferenceName, string? Notes);
public sealed record ProviderAdapterRecord(Guid Id, string Name, ProviderFamily Family, string Owner, ConfigurationEnvironment Environment, ProviderCapability Capabilities, string CredentialReferenceName, string Notes, ProviderAdapterState State, DateTimeOffset CreatedUtc, DateTimeOffset UpdatedUtc);

public static class ProviderAdapterService
{
    private const ProviderCapability KnownCapabilities = ProviderCapability.CalendarRead | ProviderCapability.EmailRead | ProviderCapability.FileRead | ProviderCapability.DraftProposal | ProviderCapability.ProviderWrite;
    public static FormValidationResult Validate(ProviderAdapterDraft draft)
    {
        List<FormFieldIssue> issues=[]; Add(issues,FormValidation.Required("adapter-name",draft.Name,"Adapter name"));Add(issues,FormValidation.MaximumLength("adapter-name",draft.Name,"Adapter name",100));Add(issues,FormValidation.SingleLine("adapter-name",draft.Name,"Adapter name"));Add(issues,FormValidation.Required("adapter-owner",draft.Owner,"Owner"));Add(issues,FormValidation.MaximumLength("adapter-owner",draft.Owner,"Owner",100));Add(issues,FormValidation.SingleLine("adapter-owner",draft.Owner,"Owner"));Add(issues,FormValidation.MaximumLength("adapter-notes",draft.Notes,"Notes",500));
        if(!Enum.IsDefined(draft.Family))issues.Add(new("adapter-family","family","Select a supported provider family."));if(!Enum.IsDefined(draft.Environment))issues.Add(new("adapter-environment","environment","Select a supported environment."));if(draft.Capabilities==ProviderCapability.None||(draft.Capabilities&~KnownCapabilities)!=0)issues.Add(new("adapter-capabilities","capabilities","Select at least one supported capability."));string reference=Clean(draft.CredentialReferenceName);if(reference.Length>0&&!IsReference(reference))issues.Add(new("adapter-credential-reference","reference-name","Use an uppercase credential-reference name, never a credential value."));if(ConfigurationReadinessService.ContainsSecretLikeValue(draft.Notes))issues.Add(new("adapter-notes","secret-like-value","Notes appear to contain a secret or credential value."));return new(issues);
    }
    public static ProviderAdapterRecord Create(ProviderAdapterDraft draft,DateTimeOffset now){if(!Validate(draft).IsValid)throw new ArgumentException("The provider-adapter record is invalid.",nameof(draft));string reference=Clean(draft.CredentialReferenceName);return Normalize(new(Guid.NewGuid(),draft.Name!.Trim(),draft.Family,draft.Owner!.Trim(),draft.Environment,draft.Capabilities,reference,Clean(draft.Notes),reference.Length==0?ProviderAdapterState.Planned:ProviderAdapterState.AvailableForCredentialedTest,now,now));}
    public static ProviderAdapterRecord SetState(ProviderAdapterRecord record,ProviderAdapterState state,DateTimeOffset now){ProviderAdapterRecord value=Normalize(record);if(!Enum.IsDefined(state))throw new ArgumentException("Select a supported adapter state.",nameof(state));if(state==ProviderAdapterState.AvailableForCredentialedTest&&value.CredentialReferenceName.Length==0)throw new InvalidOperationException("A credential reference name is required before credentialed testing.");if(state==value.State)throw new InvalidOperationException("The adapter state is already selected.");return Normalize(value with{State=state,UpdatedUtc=now});}
    public static bool ProviderWritesEnabled(ProviderAdapterRecord record)=>false;
    public static ProviderAdapterRecord Normalize(ProviderAdapterRecord record){if(record.Id==Guid.Empty||record.CreatedUtc==default||record.UpdatedUtc==default)throw new InvalidDataException("Adapter identity and timestamps are required.");if(!Enum.IsDefined(record.Family)||!Enum.IsDefined(record.Environment)||!Enum.IsDefined(record.State)||(record.Capabilities&~KnownCapabilities)!=0||record.Capabilities==ProviderCapability.None)throw new InvalidDataException("Adapter enum or capability value is invalid.");string name=Required(record.Name,"name",100),owner=Required(record.Owner,"owner",100),reference=Clean(record.CredentialReferenceName),notes=Clean(record.Notes);if(reference.Length>0&&!IsReference(reference))throw new InvalidDataException("Adapter credential reference is invalid.");if(notes.Length>500||ConfigurationReadinessService.ContainsSecretLikeValue(notes))throw new InvalidDataException("Adapter notes are unsafe.");if(record.State==ProviderAdapterState.AvailableForCredentialedTest&&reference.Length==0)throw new InvalidDataException("Credentialed-test state requires a reference name.");return record with{Name=name,Owner=owner,CredentialReferenceName=reference,Notes=notes};}
    private static bool IsReference(string value)=>value.Length is >=3 and <=100&&char.IsUpper(value[0])&&value.All(c=>char.IsUpper(c)||char.IsDigit(c)||c=='_');private static string Required(string?value,string label,int max){string r=Clean(value);if(r.Length==0||r.Length>max||r.Any(char.IsControl))throw new InvalidDataException($"Adapter {label} is invalid.");return r;}private static string Clean(string?value)=>string.IsNullOrWhiteSpace(value)?"":value.Trim();private static void Add(ICollection<FormFieldIssue>issues,FormFieldIssue?issue){if(issue is not null)issues.Add(issue);}
}
