<Project>
  <PropertyGroup>
    <Version>28.0.0-alpha.7</Version>
    <VersionPrefix>28.0.0</VersionPrefix>
    <VersionSuffix>alpha.7</VersionSuffix>
    <AssemblyVersion>28.0.0.0</AssemblyVersion>
    <FileVersion>28.0.0.0</FileVersion>
    <InformationalVersion>28.0.0-alpha.7</InformationalVersion>
    <LifeOSDisplayVersion>v28.0.0-alpha.7</LifeOSDisplayVersion>
    <LifeOSReleaseName>v28 Projects and Delivery</LifeOSReleaseName>
  </PropertyGroup>
</Project>
