using LifeOS.Core.ItemState;
using LifeOS.Core.MoneyObligations;

namespace LifeOS.Shared.MoneyObligations;

public static class MoneyObligationDemoData
{
    public static MoneyObligationProfile CreateDefaultProfile()
    {
        return new MoneyObligationProfile
        {
            Version = "v4.2",
            Mode = "Bills / Upcoming Payments / Pay Later",
            Rule = "Every bill, upcoming payment, BNPL installment, and hidden deduction is a stateful money obligation before it affects safe-to-spend.",
            RealBankSyncEnabled = false,
            RealPayLaterSyncEnabled = false,
            ManualReviewRequired = true,
            PaidRequiresEvidence = true,
            CurrentSafeToSpendBeforeObligations = 220.00m,
            Items =
            [
                Item(
                    "Power bill due this week",
                    MoneyObligationKind.Bill,
                    MoneyObligationSourceKind.Manual,
                    LifeOsItemState.DueSoon,
                    MoneyObligationPressureLevel.Critical,
                    MoneyObligationEvidenceState.SourceNoteOnly,
                    148.50m,
                    148.50m,
                    0m,
                    DateTime.Today.AddDays(3),
                    "Demo Power Provider",
                    "Utilities",
                    "One-off/statement due this week",
                    "Manual bill source note exists.",
                    "Confirm paid only after payment evidence exists.",
                    "Bill due this week reduces safe-to-spend.",
                    "Pay, defer, or budget.",
                    true,
                    true,
                    false,
                    true),

                Item(
                    "Phone plan",
                    MoneyObligationKind.Subscription,
                    MoneyObligationSourceKind.Manual,
                    LifeOsItemState.DueSoon,
                    MoneyObligationPressureLevel.High,
                    MoneyObligationEvidenceState.SourceNoteOnly,
                    35.00m,
                    35.00m,
                    35.00m,
                    DateTime.Today.AddDays(1),
                    "Demo Mobile Provider",
                    "Subscription",
                    "Monthly",
                    "Manual subscription note.",
                    "Confirm recurring amount before trusting.",
                    "Upcoming subscription affects this week's safe-to-spend.",
                    "Confirm amount and due date.",
                    true,
                    true,
                    false,
                    true),

                Item(
                    "Afterpay instalment",
                    MoneyObligationKind.PayLaterInstallment,
                    MoneyObligationSourceKind.PayLaterProvider,
                    LifeOsItemState.DueToday,
                    MoneyObligationPressureLevel.Critical,
                    MoneyObligationEvidenceState.EvidenceNeeded,
                    24.50m,
                    122.50m,
                    49.00m,
                    DateTime.Today,
                    "Demo BNPL Provider",
                    "Pay Later",
                    "Fortnightly instalment",
                    "Screenshot/receipt should be linked later.",
                    "Do not mark paid until bank/payment evidence exists.",
                    "Pay-later due today reduces safe-to-spend.",
                    "Pay or confirm payment evidence.",
                    false,
                    true,
                    true,
                    true),

                Item(
                    "Zip instalment",
                    MoneyObligationKind.PayLaterInstallment,
                    MoneyObligationSourceKind.PayLaterProvider,
                    LifeOsItemState.DueSoon,
                    MoneyObligationPressureLevel.High,
                    MoneyObligationEvidenceState.EvidenceNeeded,
                    18.00m,
                    72.00m,
                    36.00m,
                    DateTime.Today.AddDays(5),
                    "Demo Zip Provider",
                    "Pay Later",
                    "Fortnightly instalment",
                    "Manual BNPL schedule placeholder.",
                    "Review schedule before safe-to-spend.",
                    "BNPL load affects money timeline and close-out.",
                    "Add source screenshot or confirm schedule.",
                    false,
                    true,
                    true,
                    true),

                Item(
                    "Tax/GST reserve estimate",
                    MoneyObligationKind.TaxReserve,
                    MoneyObligationSourceKind.Manual,
                    LifeOsItemState.Planned,
                    MoneyObligationPressureLevel.High,
                    MoneyObligationEvidenceState.SourceNoteOnly,
                    0m,
                    0m,
                    180.00m,
                    null,
                    "Demo Reserve",
                    "Hidden deduction",
                    "Monthly estimate",
                    "Manual estimate only.",
                    "Confirm percentage/rule before treating balance as safe.",
                    "Hidden deduction missing creates safe-to-spend risk.",
                    "Review reserve rule before spending.",
                    true,
                    true,
                    true,
                    false),

                Item(
                    "ACC / student-loan / KiwiSaver custom reserve",
                    MoneyObligationKind.HiddenDeduction,
                    MoneyObligationSourceKind.Manual,
                    LifeOsItemState.NeedsReview,
                    MoneyObligationPressureLevel.High,
                    MoneyObligationEvidenceState.EvidenceNeeded,
                    0m,
                    0m,
                    95.00m,
                    null,
                    "Demo Reserve",
                    "Hidden deduction",
                    "Monthly estimate",
                    "Needs source/rule before trusted.",
                    "Confirm deduction assumptions before safe-to-spend.",
                    "Unknown deductions should reduce confidence.",
                    "Add source/rule or mark not applicable.",
                    false,
                    true,
                    true,
                    false),

                Item(
                    "Vehicle compliance renewal",
                    MoneyObligationKind.FineOrCompliance,
                    MoneyObligationSourceKind.Manual,
                    LifeOsItemState.Planned,
                    MoneyObligationPressureLevel.Medium,
                    MoneyObligationEvidenceState.NotNeededYet,
                    90.00m,
                    90.00m,
                    0m,
                    DateTime.Today.AddDays(21),
                    "Demo Agency",
                    "Compliance",
                    "Upcoming",
                    "Manual future cost placeholder.",
                    "Review amount before due week.",
                    "Future payment should be visible before it becomes urgent.",
                    "Keep planned until due window.",
                    true,
                    false,
                    false,
                    false),

                Item(
                    "Receipt imported as possible bill",
                    MoneyObligationKind.ManualCashflowItem,
                    MoneyObligationSourceKind.OcrImportLater,
                    LifeOsItemState.NeedsReview,
                    MoneyObligationPressureLevel.Medium,
                    MoneyObligationEvidenceState.EvidenceNeeded,
                    42.75m,
                    42.75m,
                    0m,
                    DateTime.Today.AddDays(2),
                    "Demo Merchant",
                    "Receipt/OCR",
                    "Imported candidate",
                    "OCR/source image exists but needs review.",
                    "Imported data is not trusted until reviewed.",
                    "Unreviewed OCR creates review pressure, not final money truth.",
                    "Accept, edit, link, or reject.",
                    false,
                    true,
                    true,
                    true),

                Item(
                    "Manual paid bill example",
                    MoneyObligationKind.Bill,
                    MoneyObligationSourceKind.Receipt,
                    LifeOsItemState.Paid,
                    MoneyObligationPressureLevel.Low,
                    MoneyObligationEvidenceState.PaymentConfirmed,
                    62.00m,
                    0m,
                    0m,
                    DateTime.Today.AddDays(-1),
                    "Demo Provider",
                    "Utilities",
                    "Paid",
                    "Receipt/payment evidence confirmed.",
                    "Paid state is allowed because evidence exists.",
                    "Paid bills reduce pressure.",
                    "Archive during weekly close-out if no longer needed.",
                    true,
                    false,
                    false,
                    false)
            ]
        };
    }

    private static MoneyObligationItem Item(
        string title,
        MoneyObligationKind kind,
        MoneyObligationSourceKind source,
        LifeOsItemState state,
        MoneyObligationPressureLevel pressure,
        MoneyObligationEvidenceState evidenceState,
        decimal amountDue,
        decimal remainingBalance,
        decimal monthlyEstimate,
        DateTime? dueDate,
        string provider,
        string category,
        string scheduleLabel,
        string evidenceSummary,
        string reviewGate,
        string pressureSignal,
        string safeNextAction,
        bool trusted,
        bool affectsSafeToSpend,
        bool isHiddenDeduction,
        bool isRequiredThisWeek)
    {
        return new MoneyObligationItem
        {
            Title = title,
            Kind = kind,
            SourceKind = source,
            State = state,
            PressureLevel = pressure,
            EvidenceState = evidenceState,
            AmountDue = amountDue,
            RemainingBalance = remainingBalance,
            MonthlyEstimate = monthlyEstimate,
            DueDate = dueDate,
            Provider = provider,
            Category = category,
            ScheduleLabel = scheduleLabel,
            EvidenceSummary = evidenceSummary,
            ReviewGate = reviewGate,
            PressureSignal = pressureSignal,
            SafeNextAction = safeNextAction,
            Trusted = trusted,
            AffectsSafeToSpend = affectsSafeToSpend,
            AffectsAgenda = dueDate.HasValue,
            AffectsWeeklyCloseOut = true,
            IsRequiredThisWeek = isRequiredThisWeek,
            IsHiddenDeduction = isHiddenDeduction,
            IsPayLater = kind is MoneyObligationKind.PayLaterInstallment or MoneyObligationKind.PayLaterBalance,
            CountsAsSafeMoney = false,
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now
        };
    }
}
