using LifeOS.Core.ConfigurationReadiness;using LifeOS.Core.ProviderAdapters;using LifeOS.Shared.Storage;
namespace LifeOS.Shared.ProviderAdapters;
public sealed class ProviderAdapterRepository
{
 private readonly VersionedJsonLocalStore<List<ProviderAdapterRecord>> _store;public ProviderAdapterRepository(string path,Func<List<ProviderAdapterRecord>>?empty=null,Func<DateTimeOffset>?utcNow=null){_store=new(path,"provider-adapters",1,empty??(()=>[]),Normalize,utcNow:utcNow);}public LocalStoreLoadResult<List<ProviderAdapterRecord>> LoadResult()=>_store.Load();public List<ProviderAdapterRecord> Load()=>LoadResult().Value;public void Save(IEnumerable<ProviderAdapterRecord>values)=>_store.Save(values.ToList());public LocalStoreHealth Inspect()=>_store.Inspect();public IReadOnlyList<LocalStoreTrashEntry> ListTrash()=>_store.ListTrash();public LocalStoreTrashEntry MoveToTrash()=>_store.MoveToTrash();public void RestoreTrash(string id)=>_store.RestoreTrash(id);private static List<ProviderAdapterRecord> Normalize(List<ProviderAdapterRecord>values)=>values.Select(ProviderAdapterService.Normalize).OrderBy(x=>x.State).ThenBy(x=>x.Name,StringComparer.OrdinalIgnoreCase).ToList();
}
public static class ProviderAdapterStorage
{
 public static string FilePath=>LocalAppDataPath.GetFilePath("provider-adapters.json");private static ProviderAdapterRepository Repo()=>new(FilePath,LocalAppDataPath.IsPortfolioDemoMode?Demo:()=>[]);public static List<ProviderAdapterRecord> Load()=>Repo().Load();public static void Save(IEnumerable<ProviderAdapterRecord>values)=>Repo().Save(values);public static LocalStoreHealth Inspect()=>Repo().Inspect();public static IReadOnlyList<LocalStoreTrashEntry> ListTrash()=>Repo().ListTrash();public static void RestoreTrash(string id)=>Repo().RestoreTrash(id);public static void Reset(){if(File.Exists(FilePath))Repo().MoveToTrash();}private static List<ProviderAdapterRecord> Demo(){DateTimeOffset now=DateTimeOffset.UtcNow;return[ProviderAdapterService.Create(new("Fictional calendar adapter",ProviderFamily.Google,"Integration owner",ConfigurationEnvironment.Test,ProviderCapability.CalendarRead|ProviderCapability.DraftProposal,"LIFEOS_DEMO_GOOGLE_TOKEN","Capability declaration only."),now.AddHours(-2)),ProviderAdapterService.Create(new("Fictional file adapter",ProviderFamily.Microsoft,"Product owner",ConfigurationEnvironment.LocalDevelopment,ProviderCapability.FileRead,null,"Not configured."),now.AddHours(-1))];}
}
