namespace LifeOS.Core.FinancialRecords;
public static class FinancialProofData
{
    public static FinancialDataset Build(DateTimeOffset now)
    {
        var today = DateOnly.FromDateTime(now.Date);
        var accounts = new[] { new FinancialAccount("acct-operating", "Fictional operating account", FinancialAccountType.Manual, "NZD", 2750m, false, FinancialReviewState.Confirmed), new FinancialAccount("acct-receivable", "Accounts receivable", FinancialAccountType.Receivable, "NZD", 830m, false, FinancialReviewState.Confirmed), new FinancialAccount("acct-card", "Sanitized business card", FinancialAccountType.Card, "NZD", -142.50m, false, FinancialReviewState.PendingReview) };
        var categories = new[] { new FinancialCategory("cat-work", "Client work", TransactionDirection.Income), new FinancialCategory("cat-software", "Software", TransactionDirection.Expense), new FinancialCategory("cat-travel", "Travel", TransactionDirection.Expense) };
        var parties = new[] { new FinancialParty("party-a", "Fictional Engineering", FinancialPartyType.Client), new FinancialParty("party-b", "Example Door Systems", FinancialPartyType.Client), new FinancialParty("party-s", "Sanitized Software Vendor", FinancialPartyType.Supplier) };
        var proof = new FinancialEvidenceLink("ev-proof", "Sanitized proof summary", "A1B2C3D4", FinancialReviewState.Confirmed);
        var transactions = new[] { new FinancialTransaction("txn-income", "proof-income-1", "acct-operating", TransactionDirection.Income, 350m, "NZD", today.AddDays(-1), "Fictional client payment", "cat-work", "party-b", FinancialReviewState.Confirmed, [new(FinancialLinkType.Work,"work-demo","Example delivery")], [proof]), new FinancialTransaction("txn-expense", "proof-expense-1", "acct-card", TransactionDirection.Expense, 42.50m, "NZD", today.AddDays(-2), "Sanitized software expense", "cat-software", "party-s", FinancialReviewState.Confirmed, [], []), new FinancialTransaction("txn-review", "proof-expense-review-1", "acct-card", TransactionDirection.Expense, 18.75m, "NZD", today, "Fictional travel item awaiting review", "cat-travel", "party-s", FinancialReviewState.PendingReview, [], []) };
        var invoices = new[] { new FinancialInvoice("inv-58-a", "INV-DEMO-058", "party-a", 480m, "NZD", today.AddDays(-10), today.AddDays(-1), InvoiceState.Overdue, 0m, FinancialReviewState.Confirmed, [new(FinancialLinkType.Work,"work-a","Welding proof review")], [proof]), new FinancialInvoice("inv-58-b", "INV-DEMO-059", "party-b", 350m, "NZD", today.AddDays(-12), today.AddDays(-3), InvoiceState.Paid, 350m, FinancialReviewState.Confirmed, [new(FinancialLinkType.Project,"project-b","Door workflow")], [proof]), new FinancialInvoice("inv-58-c", "INV-DEMO-060", "party-a", 600m, "NZD", today.AddDays(-4), today.AddDays(5), InvoiceState.PartiallyPaid, 200m, FinancialReviewState.Confirmed, [], []) };
        var payments = new[] { new FinancialPayment("pay-58-a", "inv-58-b", 350m, "NZD", today.AddDays(-2), PaymentState.Allocated, 350m, FinancialReviewState.Confirmed, [proof]), new FinancialPayment("pay-58-b", "inv-58-c", 200m, "NZD", today.AddDays(-1), PaymentState.PartiallyAllocated, 200m, FinancialReviewState.Confirmed, [proof]) };
        var audit = new[] { new FinancialAuditEntry("audit-1","Invoice","inv-58-c","Payment allocated","Fictional partial payment allocated after explicit review.",now.AddHours(-2)), new FinancialAuditEntry("audit-2","Transaction","txn-expense","Review requested","Sensitive values omitted from proof diagnostics.",now.AddMinutes(-20)) };
        return new(accounts,categories,parties,transactions,invoices,payments,audit);
    }
}
