using System.Windows; using System.Windows.Controls; using System.Windows.Controls.Primitives; using System.Windows.Media; using LifeOS.Core.Documents;
namespace LifeOS.Desktop;
public sealed class DocumentIntakeV11View:UserControl
{
 readonly DocumentIntakeService service=new(); readonly IReadOnlyList<DocumentRecord> records; readonly IReadOnlyList<DuplicateDocumentCandidate> dupes; readonly ContentControl content=new(); readonly TextBlock title=new(); readonly Dictionary<string,Button> nav=new();
 public DocumentIntakeV11View(){(records,dupes)=DocumentProofData.Build(new(2026,7,20,12,0,0,TimeSpan.FromHours(12)));Background=B("#0B1020");Foreground=Brushes.White;Content=Shell();Show("Dashboard");}
 UIElement Shell(){var g=new Grid();g.ColumnDefinitions.Add(new(){Width=new(245)});g.ColumnDefinitions.Add(new(){Width=new(1,GridUnitType.Star)});var rail=new StackPanel{Background=B("#11182B"),Margin=new(0),};rail.Children.Add(T("LIFEOS v11",12,B("#9AA9C7"),new(20,24,20,3)));rail.Children.Add(T("Documents",30,Brushes.White,new(20,0,20,18),FontWeights.Bold));foreach(var p in new[]{"Dashboard","Capture draft","Integrity","Extraction review","Accepted metadata","Duplicate review","Linked context"}){var b=new Button{Content=p,Tag=p,Margin=new(18,0,18,7),Padding=new(14,11,14,11),HorizontalContentAlignment=HorizontalAlignment.Left,Foreground=B("#D9E2F3"),Background=Brushes.Transparent,BorderBrush=Brushes.Transparent,BorderThickness=new(1),Cursor=System.Windows.Input.Cursors.Hand,Template=NavigationButtonTemplate()};b.MouseEnter+=(_,_)=>ApplyNavigationVisual(b,true);b.MouseLeave+=(_,_)=>ApplyNavigationVisual(b,false);b.Click+=(_,_)=>Show(p);nav[p]=b;rail.Children.Add(b);}g.Children.Add(rail);var main=new Grid{Margin=new(28,24,28,24)};main.RowDefinitions.Add(new(){Height=GridLength.Auto});main.RowDefinitions.Add(new(){Height=new(1,GridUnitType.Star)});title.FontSize=31;title.FontWeight=FontWeights.Bold;title.Foreground=Brushes.White;main.Children.Add(title);Grid.SetRow(content,1);main.Children.Add(content);Grid.SetColumn(main,1);g.Children.Add(main);return g;}

 static ControlTemplate NavigationButtonTemplate(){var border=new FrameworkElementFactory(typeof(Border));border.SetBinding(Border.BackgroundProperty,new System.Windows.Data.Binding(nameof(Button.Background)){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});border.SetBinding(Border.BorderBrushProperty,new System.Windows.Data.Binding(nameof(Button.BorderBrush)){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});border.SetBinding(Border.BorderThicknessProperty,new System.Windows.Data.Binding(nameof(Button.BorderThickness)){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});var presenter=new FrameworkElementFactory(typeof(ContentPresenter));presenter.SetBinding(ContentPresenter.ContentProperty,new System.Windows.Data.Binding(nameof(Button.Content)){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});presenter.SetBinding(ContentPresenter.MarginProperty,new System.Windows.Data.Binding(nameof(Button.Padding)){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});presenter.SetBinding(ContentPresenter.HorizontalAlignmentProperty,new System.Windows.Data.Binding(nameof(Button.HorizontalContentAlignment)){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});presenter.SetValue(ContentPresenter.VerticalAlignmentProperty,VerticalAlignment.Center);border.AppendChild(presenter);return new ControlTemplate(typeof(Button)){VisualTree=border};}
 void ApplyNavigationVisual(Button button,bool hover){var active=button.Tag is string page&&nav.TryGetValue(page,out var selected)&&ReferenceEquals(selected,button)&&button.Background is SolidColorBrush brush&&brush.Color==((SolidColorBrush)B("#23335A")).Color;if(active){button.Background=B("#23335A");button.BorderBrush=B("#607DFF");button.Foreground=Brushes.White;return;}button.Background=hover?B("#19233B"):Brushes.Transparent;button.BorderBrush=hover?B("#31405F"):Brushes.Transparent;button.Foreground=hover?Brushes.White:B("#D9E2F3");}
 void Show(string p){foreach(var x in nav){bool a=x.Key==p;x.Value.Background=a?B("#23335A"):Brushes.Transparent;x.Value.BorderBrush=a?B("#607DFF"):Brushes.Transparent;} title.Text=p switch{"Dashboard"=>"Document and evidence intake","Capture draft"=>"Desktop upload and Full Mobile capture draft","Integrity"=>"Original preservation and file integrity","Extraction review"=>"Extraction suggestions awaiting review","Accepted metadata"=>"Corrected classification and accepted metadata","Duplicate review"=>"Exact-hash duplicate candidate review","Linked context"=>"Accepted document links",_=>p};content.Content=Scroll(Page(p));}
 UIElement Page(string p){var s=new StackPanel();if(p=="Dashboard"){var o=service.Summarize(records,dupes);s.Children.Add(Card("Controlled intake",$"Drafts {o.Drafts}  •  Review {o.AwaitingReview}  •  Accepted {o.Accepted}\nDuplicate candidates {o.DuplicateCandidates}  •  Extraction suggestions {o.ExtractionSuggestions}","REVIEW-FIRST"));s.Children.Add(Card("Permanent boundary","Originals preserved • derivatives separate • suggestions untrusted • no autonomous financial posting","ORIGINAL-SAFE"));}
 else if(p=="Capture draft") foreach(var x in records.Where(x=>x.State==DocumentIntakeState.Draft))s.Children.Add(Card(x.Original.FileName,$"{x.Type} • {x.State}\nSource {x.Original.Source} • {x.Original.MediaType} • {x.Original.SizeBytes} bytes\nDraft can be reviewed, cancelled or deliberately uploaded.","DRAFT"));
 else if(p=="Integrity") foreach(var x in records.Take(2))s.Children.Add(Card(x.Original.FileName,$"SHA-256 {x.Original.Sha256}\nImported {x.Original.ImportedUtc:g} • source {x.Original.Source}\nTrusted original: {x.HasTrustedOriginal} • derivatives stored separately: {x.Derivatives.Count}","ORIGINAL PRESERVED"));
 else if(p=="Extraction review"){var x=records.Single(x=>x.State==DocumentIntakeState.ReviewRequired);s.Children.Add(Card(x.Original.FileName,string.Join("\n",x.Metadata.Select(m=>$"{m.Field}: {m.Value} • confidence {m.Confidence:P0} • {m.Explanation}")),"AWAITING REVIEW"));s.Children.Add(Card("Classification suggestion",string.Join("\n",x.Classifications.Select(c=>$"{c.Type} • confidence {c.Confidence:P0} • {c.Explanation}")),"SUGGESTION ONLY"));}
 else if(p=="Accepted metadata"){var x=records.Single(x=>x.State==DocumentIntakeState.Accepted);s.Children.Add(Card(x.Original.FileName,$"Classification {x.Type} • {x.State}\n"+string.Join("\n",x.Metadata.Select(m=>$"{m.Field}: {m.Value} • accepted {m.IsAccepted}")),"ACCEPTED EXPLICITLY"));}
 else if(p=="Duplicate review"){var d=dupes.Single();s.Children.Add(Card("Exact SHA-256 match",$"Incoming {d.IncomingDocumentId}\nExisting {d.ExistingDocumentId}\nHash {d.Sha256}\nConfidence {d.Confidence:P0} • state {d.State}\nNo automatic merge, deletion or replacement.","CANDIDATE ONLY"));}
 else {var x=records.Single(x=>x.State==DocumentIntakeState.Accepted);foreach(var l in x.Links)s.Children.Add(Card(l.Label,$"Area {l.Area} • record {l.RecordId}\nRead-only document link; no autonomous posting.","LINKED"));}return s;}
 Border Card(string h,string body,string badge){var sp=new StackPanel();sp.Children.Add(T(h,20,Brushes.White,new(0),FontWeights.SemiBold));sp.Children.Add(T(body,13,B("#B8C5DE"),new(0,7,0,0)));sp.Children.Add(T(badge,11,B("#9EB8FF"),new(0,8,0,0),FontWeights.Bold));return new(){Background=B("#17213A"),BorderBrush=B("#31405F"),BorderThickness=new(1),CornerRadius=new(12),Padding=new(18),Margin=new(0,0,0,12),Child=sp};}
 static ScrollViewer Scroll(UIElement e)=>new(){Content=e,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}; static TextBlock T(string x,double z,Brush c,Thickness m,FontWeight? w=null)=>new(){Text=x,FontSize=z,Foreground=c,Margin=m,FontWeight=w??FontWeights.Normal,TextWrapping=TextWrapping.Wrap}; static SolidColorBrush B(string x)=>new((Color)ColorConverter.ConvertFromString(x));
}
