<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LifeOS.Shared\LifeOS.Shared.csproj" />
    <ProjectReference Include="..\src\LifeOS.Companion.Core\LifeOS.Companion.Core.csproj" />
    <ProjectReference Include="..\src\LifeOS.Core\LifeOS.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Label="CurrentProductVersion">
    <Version>18.0.0-beta.1</Version>
    <AssemblyVersion>18.0.0.0</AssemblyVersion>
    <FileVersion>18.0.0.0</FileVersion>
    <InformationalVersion>18.0.0-beta.1</InformationalVersion>
  </PropertyGroup></Project>
