using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Media;
using LifeOS.Core.Forms;
using LifeOS.Core.RelationshipRadar;
using LifeOS.Shared.RelationshipRadar;
using LifeOS.Shared.Storage;

namespace LifeOS.Desktop;

public sealed class RelationshipWorkspaceView : UserControl
{
    private readonly bool _demo; private List<RelationshipRadarProfile> _profiles = []; private IReadOnlyList<FormFieldIssue> _issues = []; private UserFacingProblem? _problem; private string? _notice;
    private string _name = "", _context = "", _last = "", _nextDate = "", _linked = "", _action = "", _notes = ""; private RelationshipWaitingOn _waiting = RelationshipWaitingOn.Unknown; private bool _doNotChase;
    public RelationshipWorkspaceView(bool demo) { _demo = demo; Background = Brush("#0C1220"); Foreground = Brushes.White; FontFamily = new FontFamily("Segoe UI"); try { _profiles = RelationshipRadarStorage.Load(); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException) { _problem = UserFacingProblemFactory.FromException(ex, "load relationship context"); } Render(); }
    private void Render()
    {
        DateOnly today = DateOnly.FromDateTime(DateTime.Today); RelationshipRadarSummary summary = RelationshipRadarCalculator.Calculate(_profiles, today); StackPanel root = new() { Margin = new Thickness(24) };
        root.Children.Add(Text(_demo ? "PORTFOLIO DEMO • ISOLATED" : "ORDINARY MODE • LOCAL RELATIONSHIPS", 11, "#AFA4FF", FontWeights.SemiBold)); root.Children.Add(Text("Relationships & Contact Context", 30, "#FFFFFF", FontWeights.Bold)); root.Children.Add(Text("Keep relationship context, waiting state and the next respectful action visible. Nothing sends, chases, imports contacts or changes a provider account automatically.", 14, "#B8C5D8")); if (_notice is not null) root.Children.Add(Text(_notice, 12, "#83D4B3", FontWeights.SemiBold)); if (_problem is not null) root.Children.Add(Problem(_problem));
        WrapPanel metrics = new() { Margin = new Thickness(0, 16, 0, 8) }; metrics.Children.Add(Metric("Open", summary.TotalProfiles.ToString(), "Visible context")); metrics.Children.Add(Metric("Waiting on them", summary.WaitingOnThemCount.ToString(), "No automatic chase")); metrics.Children.Add(Metric("Waiting on me", summary.WaitingOnMeCount.ToString(), "Review required")); metrics.Children.Add(Metric("Follow-up due", summary.FollowUpDueCount.ToString(), "Local date only")); metrics.Children.Add(Metric("Do not chase", summary.DoNotChaseCount.ToString(), "Explicit boundary")); root.Children.Add(metrics); root.Children.Add(Capture()); root.Children.Add(Heading("Relationship context", 21, new Thickness(0, 20, 0, 6)));
        if (_profiles.Count == 0) root.Children.Add(Card("No relationship profiles yet", "Ordinary mode does not seed people, organizations, contact history or follow-up commitments.", "#151F30")); else foreach (var profile in _profiles) root.Children.Add(ProfileCard(profile));
        LocalStoreHealth health = RelationshipRadarStorage.Inspect(); root.Children.Add(Heading("Local-data boundary", 21, new Thickness(0, 20, 0, 6))); root.Children.Add(Card("Versioned relationship-radar store", $"State: {health.State}. Recovery is available in Local Data & Recovery. No contact import, reminder, email, message, calendar or provider write occurs.", "#152437")); Content = new ScrollViewer { VerticalScrollBarVisibility = ScrollBarVisibility.Auto, HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled, Content = root };
    }
    private UIElement Capture()
    {
        StackPanel body = new(); body.Children.Add(Heading("Add relationship context", 20)); body.Children.Add(Text("Required fields are validated before authoritative memory or disk changes.", 12, "#A9B6CA")); WrapPanel a = new(); a.Children.Add(Input("Name *", "relationship-name", "Relationship.Name", _name, v => _name = v, 480)); a.Children.Add(Input("Role or context *", "relationship-context", "Relationship.Context", _context, v => _context = v, 500)); body.Children.Add(a); WrapPanel b = new(); b.Children.Add(Choice("Waiting on", "Relationship.Waiting", Enum.GetValues<RelationshipWaitingOn>(), _waiting, v => _waiting = v, 300)); b.Children.Add(Input("Last contact (YYYY-MM-DD)", "relationship-last-contact", "Relationship.LastContact", _last, v => _last = v, 330)); b.Children.Add(Input("Next follow-up (YYYY-MM-DD)", "relationship-next-follow-up", "Relationship.NextFollowUp", _nextDate, v => _nextDate = v, 330)); body.Children.Add(b); body.Children.Add(Input("Linked work", "relationship-linked-work", "Relationship.LinkedWork", _linked, v => _linked = v, 990)); body.Children.Add(Input("Next action *", "relationship-next-action", "Relationship.NextAction", _action, v => _action = v, 990)); body.Children.Add(Input("Notes", "relationship-notes", "Relationship.Notes", _notes, v => _notes = v, 990)); CheckBox donot = new() { Content = "Do not chase", IsChecked = _doNotChase, Foreground = Brushes.White, Margin = new Thickness(0, 8, 0, 0) }; AutomationProperties.SetAutomationId(donot, "Relationship.DoNotChase"); donot.Checked += (_, _) => _doNotChase = true; donot.Unchecked += (_, _) => _doNotChase = false; body.Children.Add(donot); Button add = Button("Add relationship context", "Relationship.Add", false); add.Click += (_, _) => Add(); body.Children.Add(add); return Panel(body, new Thickness(0, 14, 0, 0));
    }
    private void Add()
    {
        RelationshipRadarDraft draft = new(_name, _context, _waiting, _last, _nextDate, _linked, _action, _notes, _doNotChase); FormValidationResult validation = RelationshipRadarService.Validate(draft); _issues = validation.Issues; if (!validation.IsValid) { _problem = new UserFacingProblem("relationship-validation-failed", "Review the relationship fields", "No relationship context was added because one or more fields are invalid.", "Correct the highlighted fields, then try again.", true); Render(); return; }
        try { var profile = RelationshipRadarService.Create(draft, DateTimeOffset.Now); var candidate = _profiles.Append(profile).ToList(); RelationshipRadarStorage.Save(candidate); _profiles = candidate; _name = _context = _linked = _action = _notes = ""; _last = _nextDate = ""; _issues = []; _problem = null; _notice = $"Added {profile.Name}."; Render(); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException or InvalidDataException) { _problem = UserFacingProblemFactory.FromException(ex, "save relationship context"); Render(); }
    }
    private UIElement ProfileCard(RelationshipRadarProfile p) { StackPanel body = new(); DockPanel header = new(); TextBlock state = Text(p.Status.ToString().ToUpperInvariant(), 11, "#AFA4FF", FontWeights.SemiBold); DockPanel.SetDock(state, Dock.Right); header.Children.Add(state); header.Children.Add(Heading(p.Name, 18)); body.Children.Add(header); body.Children.Add(Text($"{p.RoleOrContext} • waiting: {p.WaitingOn}" + (p.NextFollowUpDate is null ? "" : $" • follow-up {p.NextFollowUpDate:yyyy-MM-dd}"), 12, "#A9B6CA")); body.Children.Add(Text($"Next: {p.NextAction}", 13, "#E7ECF4", FontWeights.SemiBold)); if (!string.IsNullOrWhiteSpace(p.LinkedWork)) body.Children.Add(Text($"Linked: {p.LinkedWork}", 11, "#A9B6CA")); WrapPanel actions = new(); foreach ((string label, RelationshipRadarStatus next) in Actions(p.Status).Where(action => action.Item2 != p.Status)) { Button button = Button(label, $"Relationship.State.{next}.{p.Id:N}", true); button.Click += (_, _) => Transition(p, next); actions.Children.Add(button); } body.Children.Add(actions); return Panel(body, new Thickness(0, 8, 0, 0)); }
    private static IReadOnlyList<(string, RelationshipRadarStatus)> Actions(RelationshipRadarStatus s) => s switch { RelationshipRadarStatus.Active or RelationshipRadarStatus.WaitingOnThem or RelationshipRadarStatus.WaitingOnMe or RelationshipRadarStatus.FollowUpDue => [("Waiting on them", RelationshipRadarStatus.WaitingOnThem), ("Waiting on me", RelationshipRadarStatus.WaitingOnMe), ("Do not chase", RelationshipRadarStatus.DoNotChaseYet), ("Park", RelationshipRadarStatus.Parked), ("Close", RelationshipRadarStatus.Closed)], RelationshipRadarStatus.DoNotChaseYet or RelationshipRadarStatus.Parked => [("Activate", RelationshipRadarStatus.Active), ("Close", RelationshipRadarStatus.Closed)], RelationshipRadarStatus.Closed => [("Reopen", RelationshipRadarStatus.Active)], _ => [] };
    private void Transition(RelationshipRadarProfile p, RelationshipRadarStatus next) { try { var changed = RelationshipRadarService.Transition(p, next, DateTimeOffset.Now); var candidate = _profiles.Select(v => v.Id == p.Id ? changed : v).ToList(); RelationshipRadarStorage.Save(candidate); _profiles = candidate; _notice = $"{p.Name} is now {next}."; _problem = null; Render(); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException or InvalidDataException or InvalidOperationException) { _problem = UserFacingProblemFactory.FromException(ex, "change relationship state"); Render(); } }
    private UIElement Input(string label, string fieldId, string id, string value, Action<string> changed, double width) { StackPanel field = new() { Width = width, Margin = new Thickness(0, 7, 10, 0) }; field.Children.Add(Text(label, 12, "#C7D2E3", FontWeights.SemiBold)); TextBox input = new() { Text = value, MinHeight = 38, Background = Brush("#101827"), Foreground = Brushes.White, BorderBrush = Brush("#3A4B66"), Padding = new Thickness(10, 7, 10, 7) }; AutomationProperties.SetAutomationId(input, id); input.TextChanged += (_, _) => changed(input.Text); field.Children.Add(input); string error = string.Join(" ", _issues.Where(i => i.FieldId == fieldId).Select(i => i.Message)); if (error.Length > 0) field.Children.Add(Text(error, 11, "#FF7788", FontWeights.SemiBold)); return field; }
    private static UIElement Choice<T>(string label, string id, IReadOnlyList<T> values, T selected, Action<T> changed, double width) where T : struct { StackPanel field = new() { Width = width, Margin = new Thickness(0, 7, 10, 0) }; field.Children.Add(Text(label, 12, "#C7D2E3", FontWeights.SemiBold)); ComboBox input = new() { ItemsSource = values, SelectedItem = selected, MinHeight = 38 }; AutomationProperties.SetAutomationId(input, id); input.SelectionChanged += (_, _) => { if (input.SelectedItem is T value) changed(value); }; field.Children.Add(input); return field; }
    private static Border Problem(UserFacingProblem p) { StackPanel body = new(); body.Children.Add(Heading($"{p.Title} ({p.Code})", 16)); body.Children.Add(Text(p.Detail, 12, "#E1E7F0")); body.Children.Add(Text($"Next: {p.RecoveryAction}", 12, "#C5AECF")); return new Border { Background = Brush("#251925"), BorderBrush = Brush("#C95F75"), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(9), Padding = new Thickness(15), Margin = new Thickness(0, 12, 0, 0), Child = body }; }
    private static Button Button(string label, string id, bool secondary) { Button b = new() { Content = label, Background = Brush(secondary ? "#25334A" : "#315E91"), Foreground = Brushes.White, BorderBrush = Brush(secondary ? "#405472" : "#477DB4"), Padding = new Thickness(14, 7, 14, 7), Margin = new Thickness(0, 8, 8, 0), MinHeight = 36 }; AutomationProperties.SetAutomationId(b, id); return b; }
    private static Border Metric(string label, string value, string detail) { StackPanel c = new(); c.Children.Add(Text(label, 11, "#9EACC0")); c.Children.Add(Text(value, 22, "#FFFFFF", FontWeights.SemiBold)); c.Children.Add(Text(detail, 11, "#9EACC0")); return new Border { Width = 190, MinHeight = 100, Background = Brush("#151F30"), BorderBrush = Brush("#31445F"), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(9), Padding = new Thickness(14), Margin = new Thickness(0, 0, 10, 10), Child = c }; }
    private static Border Card(string title, string body, string bg) { StackPanel c = new(); c.Children.Add(Heading(title, 16)); c.Children.Add(Text(body, 12, "#C2CDDC")); return new Border { Background = Brush(bg), BorderBrush = Brush("#31445F"), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(9), Padding = new Thickness(16), Margin = new Thickness(0, 8, 0, 0), Child = c }; }
    private static Border Panel(UIElement c, Thickness m) => new() { Background = Brush("#151F30"), BorderBrush = Brush("#31445F"), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(9), Padding = new Thickness(16), Margin = m, Child = c }; private static TextBlock Heading(string t, double s, Thickness? m = null) => new() { Text = t, FontSize = s, FontWeight = FontWeights.SemiBold, Foreground = Brushes.White, TextWrapping = TextWrapping.Wrap, Margin = m ?? new Thickness(0, 0, 0, 4) }; private static TextBlock Text(string t, double s, string c, FontWeight? w = null) => new() { Text = t, FontSize = s, FontWeight = w ?? FontWeights.Normal, Foreground = Brush(c), TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 3, 0, 0) }; private static SolidColorBrush Brush(string v) => new((Color)ColorConverter.ConvertFromString(v));
}
