using System.Diagnostics; using System.Net; using System.Security.Cryptography; using System.Text; using System.Text.Json; using LifeOS.Shared.IntegrationConnectors.GoogleCalendar;
namespace LifeOS.Shared.IntegrationConnectors.Gmail;
public sealed class GmailOAuthPkceClient(HttpClient http,GmailConnectorConfiguration config)
{
 public const string ReadOnlyScope="https://www.googleapis.com/auth/gmail.readonly";
 public async Task ConnectAsync(CancellationToken ct=default){config.Validate(); var verifier=B64(RandomNumberGenerator.GetBytes(64)); var challenge=B64(SHA256.HashData(Encoding.ASCII.GetBytes(verifier))); var state=B64(RandomNumberGenerator.GetBytes(32)); using var listener=new HttpListener(); listener.Prefixes.Add(config.RedirectUri); listener.Start(); var url="https://accounts.google.com/o/oauth2/v2/auth"+$"?client_id={Uri.EscapeDataString(config.ClientId)}&redirect_uri={Uri.EscapeDataString(config.RedirectUri)}&response_type=code&scope={Uri.EscapeDataString(ReadOnlyScope)}&access_type=offline&prompt=consent&state={Uri.EscapeDataString(state)}&code_challenge={Uri.EscapeDataString(challenge)}&code_challenge_method=S256"; Process.Start(new ProcessStartInfo(url){UseShellExecute=true}); var task=listener.GetContextAsync(); if(await Task.WhenAny(task,Task.Delay(TimeSpan.FromMinutes(5),ct))!=task) throw new TimeoutException("Gmail connection timed out."); var ctx=await task; var q=ctx.Request.QueryString; var bytes=Encoding.UTF8.GetBytes("<html><body><h2>LifeOS received the Gmail authorization response. You can close this tab.</h2></body></html>"); ctx.Response.ContentType="text/html; charset=utf-8"; ctx.Response.ContentLength64=bytes.Length; await ctx.Response.OutputStream.WriteAsync(bytes,ct); ctx.Response.Close(); if(!string.IsNullOrWhiteSpace(q["error"])) throw new InvalidOperationException("Google authorization was cancelled or denied."); if(q["state"]!=state) throw new InvalidOperationException("Google authorization state check failed."); var code=q["code"]??throw new InvalidOperationException("Google authorization code was not returned."); using var response=await http.PostAsync("https://oauth2.googleapis.com/token",new FormUrlEncodedContent(new Dictionary<string,string>{{"client_id",config.ClientId},{"client_secret",config.ClientSecret},{"code",code},{"code_verifier",verifier},{"grant_type","authorization_code"},{"redirect_uri",config.RedirectUri}}),ct); var body=await response.Content.ReadAsStringAsync(ct); if(!response.IsSuccessStatusCode) throw new InvalidOperationException($"Google token exchange failed ({(int)response.StatusCode})."); GmailOAuthTokenStore.Save(Parse(body,""));}
 public async Task<string> GetAccessTokenAsync(CancellationToken ct=default){var token=GmailOAuthTokenStore.Load()??throw new InvalidOperationException("Gmail is not connected."); if(token.IsUsable(DateTimeOffset.Now))return token.AccessToken; if(string.IsNullOrWhiteSpace(token.RefreshToken))throw new InvalidOperationException("Gmail authorization expired. Reconnect."); using var r=await http.PostAsync("https://oauth2.googleapis.com/token",new FormUrlEncodedContent(new Dictionary<string,string>{{"client_id",config.ClientId},{"client_secret",config.ClientSecret},{"refresh_token",token.RefreshToken},{"grant_type","refresh_token"}}),ct); var body=await r.Content.ReadAsStringAsync(ct); if(!r.IsSuccessStatusCode)throw new InvalidOperationException($"Google token refresh failed ({(int)r.StatusCode})."); var refreshed=Parse(body,token.RefreshToken); GmailOAuthTokenStore.Save(refreshed); return refreshed.AccessToken;}
 static GoogleOAuthToken Parse(string body,string existing){using var d=JsonDocument.Parse(body);var r=d.RootElement;return new GoogleOAuthToken{AccessToken=r.GetProperty("access_token").GetString()??"",RefreshToken=r.TryGetProperty("refresh_token",out var x)?x.GetString()??existing:existing,ExpiresAt=DateTimeOffset.Now.AddSeconds(r.TryGetProperty("expires_in",out var e)?e.GetInt32():3600),Scope=r.TryGetProperty("scope",out var s)?s.GetString()??ReadOnlyScope:ReadOnlyScope,TokenType="Bearer"};}
 static string B64(byte[] b)=>Convert.ToBase64String(b).TrimEnd('=').Replace('+','-').Replace('/','_');
}
