using System.Net.Http.Headers; using System.Text.Json; using LifeOS.Core.IntegrationConnectors.Gmail;
namespace LifeOS.Shared.IntegrationConnectors.Gmail;
public sealed class GmailApiProvider(HttpClient http,Func<Task<string>> tokenFactory):IReadOnlyGmailProvider
{
 public async Task<GmailFetchResult> SearchAsync(GmailSearchPlan plan,CancellationToken ct=default){var token=await tokenFactory(); var ids=new List<(string id,string thread)>(); using(var req=new HttpRequestMessage(HttpMethod.Get,$"https://gmail.googleapis.com/gmail/v1/users/me/messages?q={Uri.EscapeDataString(plan.GeneratedQuery)}&maxResults={plan.Request.MaxResults}")){req.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token); using var res=await http.SendAsync(req,ct); if(!res.IsSuccessStatusCode)throw new InvalidOperationException($"Gmail read-only search failed ({(int)res.StatusCode})."); using var d=JsonDocument.Parse(await res.Content.ReadAsStringAsync(ct)); if(d.RootElement.TryGetProperty("messages",out var arr))foreach(var x in arr.EnumerateArray().Take(plan.Request.MaxResults))ids.Add((x.GetProperty("id").GetString()??"",x.GetProperty("threadId").GetString()??""));}
 var result=new List<GmailProviderMessage>();int skipped=0; foreach(var item in ids){try{using var req=new HttpRequestMessage(HttpMethod.Get,$"https://gmail.googleapis.com/gmail/v1/users/me/messages/{item.id}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Cc&metadataHeaders=Subject&metadataHeaders=Date");req.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);using var res=await http.SendAsync(req,ct);if(!res.IsSuccessStatusCode){skipped++;continue;}using var d=JsonDocument.Parse(await res.Content.ReadAsStringAsync(ct));var root=d.RootElement;var headers=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);if(root.TryGetProperty("payload",out var p)&&p.TryGetProperty("headers",out var hs))foreach(var h in hs.EnumerateArray())headers[h.GetProperty("name").GetString()??""]=h.GetProperty("value").GetString()??"";var sent=DateTimeOffset.TryParse(headers.GetValueOrDefault("Date"),out var parsed)?parsed:DateTimeOffset.FromUnixTimeMilliseconds(long.Parse(root.GetProperty("internalDate").GetString()??"0"));var labels=root.TryGetProperty("labelIds",out var l)?l.EnumerateArray().Select(x=>x.GetString()??"").ToList():[];result.Add(new(item.id,item.thread,sent,headers.GetValueOrDefault("From",string.Empty),Split(headers.GetValueOrDefault("To",string.Empty)),Split(headers.GetValueOrDefault("Cc",string.Empty)),headers.GetValueOrDefault("Subject",string.Empty),root.TryGetProperty("snippet",out var sn)?sn.GetString()??"":"",p.TryGetProperty("parts",out var parts)&&parts.EnumerateArray().Any(x=>x.TryGetProperty("filename",out var f)&&!string.IsNullOrWhiteSpace(f.GetString())),labels));}catch{skipped++;}}
 return new GmailFetchResult(result,skipped,skipped>0,skipped>0?"Some Gmail messages could not be normalized.":"");}
 static IReadOnlyList<string> Split(string value)=>value.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);
}
