using LifeOS.Core.ItemState;

namespace LifeOS.Shared.ItemState;

public static class LifeOsItemStateDemoData
{
    public static LifeOsItemStateProfile CreateDefaultProfile()
    {
        return new LifeOsItemStateProfile
        {
            Version = "v4.1",
            Mode = "Item Type / State Engine",
            MasterRule = "Everything important becomes an item. Every item has state. Every state affects pressure. Every pressure feeds the Command Centre.",
            RealIntegrationsEnabled = false,
            ItemStateEngineActive = true,
            ManualReviewRequired = true,
            EvidenceBeforeTrustedState = true,
            Items =
            [
                Item(
                    "Power bill due this week",
                    LifeOsItemType.Bill,
                    LifeOsItemState.DueSoon,
                    LifeOsItemSourceKind.Manual,
                    LifeOsItemRiskLevel.Critical,
                    148.50m,
                    DateTime.Today.AddDays(3),
                    "Demo Power Provider",
                    "",
                    "Manual bill item with source note.",
                    "Confirm paid only after payment evidence exists.",
                    "Bills due reduce safe-to-spend and create weekly money pressure.",
                    "Pay, defer, or budget.",
                    true,
                    true,
                    true,
                    true,
                    LifeOsItemImpactArea.Money,
                    LifeOsItemImpactArea.Time,
                    LifeOsItemImpactArea.WeeklyCloseOut,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Afterpay instalment",
                    LifeOsItemType.PayLater,
                    LifeOsItemState.DueToday,
                    LifeOsItemSourceKind.PayLater,
                    LifeOsItemRiskLevel.Critical,
                    24.50m,
                    DateTime.Today,
                    "Demo BNPL Provider",
                    "",
                    "Screenshot or receipt should be linked later.",
                    "Do not mark paid until bank/payment evidence exists.",
                    "Pay-later due today reduces safe-to-spend.",
                    "Pay or confirm payment evidence.",
                    false,
                    true,
                    true,
                    true,
                    LifeOsItemImpactArea.Money,
                    LifeOsItemImpactArea.Time,
                    LifeOsItemImpactArea.WeeklyCloseOut,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Receipt OCR needs review",
                    LifeOsItemType.Receipt,
                    LifeOsItemState.NeedsReview,
                    LifeOsItemSourceKind.ReceiptOcr,
                    LifeOsItemRiskLevel.High,
                    37.90m,
                    DateTime.Today,
                    "Demo Merchant",
                    "",
                    "Original image is evidence; OCR result is untrusted.",
                    "Review OCR before creating a payment or proof item.",
                    "Unreviewed OCR creates review pressure, not final money truth.",
                    "Accept, edit, link, or reject OCR output.",
                    false,
                    true,
                    false,
                    true,
                    LifeOsItemImpactArea.Evidence,
                    LifeOsItemImpactArea.IntegrationInbox,
                    LifeOsItemImpactArea.Money,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Client invoice sent",
                    LifeOsItemType.Invoice,
                    LifeOsItemState.PaymentExpected,
                    LifeOsItemSourceKind.WorkPipeline,
                    LifeOsItemRiskLevel.High,
                    420.00m,
                    DateTime.Today.AddDays(7),
                    "Demo Client",
                    "Demo Proof Project",
                    "Linked work session and proof notes.",
                    "Payment expected is not safe money until paid.",
                    "Expected income is not safe-to-spend.",
                    "Wait, follow up later, or mark paid only with evidence.",
                    true,
                    false,
                    false,
                    true,
                    LifeOsItemImpactArea.Money,
                    LifeOsItemImpactArea.Work,
                    LifeOsItemImpactArea.WeeklyCloseOut,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Warm lead waiting on reply",
                    LifeOsItemType.WorkPipeline,
                    LifeOsItemState.Waiting,
                    LifeOsItemSourceKind.WorkPipeline,
                    LifeOsItemRiskLevel.Medium,
                    null,
                    DateTime.Today.AddDays(2),
                    "Demo Contact",
                    "Demo Opportunity",
                    "Manual pipeline item.",
                    "Do not chase until follow-up date.",
                    "Waiting work affects work pressure but should not create noise before follow-up date.",
                    "Wait or schedule follow-up.",
                    true,
                    false,
                    true,
                    true,
                    LifeOsItemImpactArea.Work,
                    LifeOsItemImpactArea.People,
                    LifeOsItemImpactArea.Time,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Work session ready for invoice",
                    LifeOsItemType.WorkSession,
                    LifeOsItemState.Invoiced,
                    LifeOsItemSourceKind.TimerAgent,
                    LifeOsItemRiskLevel.High,
                    180.00m,
                    null,
                    "Demo Client",
                    "Demo Work Session",
                    "Work session proof exists.",
                    "Invoice/work summary should link to proof.",
                    "Invoice-ready work creates work and money pressure.",
                    "Confirm invoice state and payment follow-up date.",
                    true,
                    false,
                    false,
                    true,
                    LifeOsItemImpactArea.Work,
                    LifeOsItemImpactArea.Proof,
                    LifeOsItemImpactArea.Money,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Follow-up due",
                    LifeOsItemType.FollowUp,
                    LifeOsItemState.DueToday,
                    LifeOsItemSourceKind.EmailProfile,
                    LifeOsItemRiskLevel.High,
                    null,
                    DateTime.Today,
                    "Demo Contact",
                    "Demo Client Thread",
                    "Thread profile exists, but no live email sync.",
                    "Manual confirmation before sending.",
                    "Follow-up due affects people/work pressure.",
                    "Send, wait, or mark do-not-chase.",
                    true,
                    false,
                    true,
                    true,
                    LifeOsItemImpactArea.People,
                    LifeOsItemImpactArea.Work,
                    LifeOsItemImpactArea.Time,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Calendar item imported later",
                    LifeOsItemType.AgendaItem,
                    LifeOsItemState.Planned,
                    LifeOsItemSourceKind.CalendarImport,
                    LifeOsItemRiskLevel.Medium,
                    null,
                    DateTime.Today.AddDays(1),
                    "Demo Calendar",
                    "",
                    "Future calendar item placeholder.",
                    "Imported events require review before trust.",
                    "Calendar should inform daily load, not take control.",
                    "Review event and link to person/project if needed.",
                    false,
                    false,
                    true,
                    true,
                    LifeOsItemImpactArea.Time,
                    LifeOsItemImpactArea.People,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Proof item missing screenshot",
                    LifeOsItemType.ProofItem,
                    LifeOsItemState.Open,
                    LifeOsItemSourceKind.Manual,
                    LifeOsItemRiskLevel.Medium,
                    null,
                    null,
                    "",
                    "Demo Portfolio Item",
                    "Proof note exists, screenshot missing.",
                    "Proof confidence needs evidence.",
                    "Missing proof creates close-out pressure.",
                    "Attach screenshot or close as not needed.",
                    false,
                    false,
                    false,
                    true,
                    LifeOsItemImpactArea.Proof,
                    LifeOsItemImpactArea.Evidence,
                    LifeOsItemImpactArea.WeeklyCloseOut,
                    LifeOsItemImpactArea.CommandCentre),

                Item(
                    "Future integration preview",
                    LifeOsItemType.IntegrationPreview,
                    LifeOsItemState.NeedsReview,
                    LifeOsItemSourceKind.FutureIntegration,
                    LifeOsItemRiskLevel.High,
                    null,
                    DateTime.Today,
                    "Demo Provider",
                    "",
                    "Represents imported data before trust.",
                    "External data lands in review queue first.",
                    "Unreviewed imported data is review pressure, not final truth.",
                    "Accept, reject, link, or archive.",
                    false,
                    false,
                    false,
                    true,
                    LifeOsItemImpactArea.IntegrationInbox,
                    LifeOsItemImpactArea.Evidence,
                    LifeOsItemImpactArea.CommandCentre)
            ],
            TransitionRules =
            [
                Rule(LifeOsItemType.Bill, LifeOsItemState.Open, LifeOsItemState.DueSoon, "Bill approaching", "Due date is inside warning window.", "Increases money pressure.", false, true, false),
                Rule(LifeOsItemType.Bill, LifeOsItemState.DueToday, LifeOsItemState.Paid, "Mark bill paid", "Payment evidence or trusted note exists.", "Reduces money pressure.", true, true, false),
                Rule(LifeOsItemType.PayLater, LifeOsItemState.DueToday, LifeOsItemState.Paid, "Mark BNPL paid", "Payment evidence exists.", "Reduces pay-later and safe-to-spend pressure.", true, true, false),
                Rule(LifeOsItemType.Receipt, LifeOsItemState.NeedsReview, LifeOsItemState.Confirmed, "Confirm OCR receipt", "OCR fields reviewed manually.", "Creates trusted money/evidence state.", true, true, false),
                Rule(LifeOsItemType.Invoice, LifeOsItemState.Invoiced, LifeOsItemState.PaymentExpected, "Payment expected", "Invoice sent and due date known.", "Creates expected income, not safe money.", true, true, false),
                Rule(LifeOsItemType.Invoice, LifeOsItemState.PaymentExpected, LifeOsItemState.Paid, "Mark invoice paid", "Payment received evidence exists.", "Moves expected income to confirmed paid.", true, true, false),
                Rule(LifeOsItemType.FollowUp, LifeOsItemState.Waiting, LifeOsItemState.DueToday, "Follow-up due", "Follow-up date has arrived.", "Creates follow-up pressure.", false, true, false),
                Rule(LifeOsItemType.FollowUp, LifeOsItemState.DueToday, LifeOsItemState.DoNotChase, "Do not chase", "Reason to wait has been recorded.", "Reduces noisy follow-up pressure.", false, true, false),
                Rule(LifeOsItemType.WorkPipeline, LifeOsItemState.Blocked, LifeOsItemState.Open, "Unblock work", "Blocker removed or next action found.", "Moves work back into active pressure.", false, true, false),
                Rule(LifeOsItemType.IntegrationPreview, LifeOsItemState.NeedsReview, LifeOsItemState.Confirmed, "Accept import", "Imported item reviewed and mapped.", "Creates trusted LifeOS item.", true, true, false),
                Rule(LifeOsItemType.IntegrationPreview, LifeOsItemState.NeedsReview, LifeOsItemState.Ignored, "Reject import", "Imported item is irrelevant or unsafe.", "Removes review queue pressure.", false, true, true),
                Rule(LifeOsItemType.WeeklyCloseOutItem, LifeOsItemState.Open, LifeOsItemState.Closed, "Close week item", "Open loop reviewed.", "Reduces weekly close-out pressure.", false, true, false)
            ]
        };
    }

    private static LifeOsStatefulItem Item(
        string title,
        LifeOsItemType type,
        LifeOsItemState state,
        LifeOsItemSourceKind source,
        LifeOsItemRiskLevel risk,
        decimal? amount,
        DateTime? dueDate,
        string personOrProvider,
        string linkedProject,
        string evidenceSummary,
        string reviewGate,
        string pressureSignal,
        string safeNextAction,
        bool trusted,
        bool affectsSafeToSpend,
        bool affectsAgenda,
        bool affectsWeeklyCloseOut,
        params LifeOsItemImpactArea[] impactAreas)
    {
        return new LifeOsStatefulItem
        {
            Title = title,
            Type = type,
            State = state,
            SourceKind = source,
            RiskLevel = risk,
            Amount = amount,
            DueDate = dueDate,
            PersonOrProvider = personOrProvider,
            LinkedProject = linkedProject,
            EvidenceSummary = evidenceSummary,
            ReviewGate = reviewGate,
            PressureSignal = pressureSignal,
            SafeNextAction = safeNextAction,
            Trusted = trusted,
            AffectsSafeToSpend = affectsSafeToSpend,
            AffectsAgenda = affectsAgenda,
            AffectsWeeklyCloseOut = affectsWeeklyCloseOut,
            AffectsCommandCentre = impactAreas.Contains(LifeOsItemImpactArea.CommandCentre),
            ImpactAreas = impactAreas.ToList(),
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now
        };
    }

    private static LifeOsStateTransitionRule Rule(
        LifeOsItemType type,
        LifeOsItemState from,
        LifeOsItemState to,
        string label,
        string requirement,
        string resultingPressure,
        bool requiresEvidence,
        bool requiresManualReview,
        bool isDestructive)
    {
        return new LifeOsStateTransitionRule
        {
            Type = type,
            FromState = from,
            ToState = to,
            Label = label,
            Requirement = requirement,
            ResultingPressure = resultingPressure,
            RequiresEvidence = requiresEvidence,
            RequiresManualReview = requiresManualReview,
            IsDestructive = isDestructive
        };
    }
}
