using System.Text.Json; using LifeOS.Core.ConfigurationReadiness; using LifeOS.Core.ProviderAdapters; using LifeOS.Core.ProviderConsent; using LifeOS.Shared.ProviderConsent; using Xunit;
namespace LifeOS.Core.Tests;
public sealed class Groups205To208ProviderConsentTests
{
 static readonly DateOnly Today=new(2026,8,18);static readonly DateTimeOffset Now=new(2026,8,18,4,5,6,TimeSpan.Zero);static ProviderConsentDraft Draft()=>new("Calendar review",ProviderFamily.Google,"Integration owner",ConfigurationEnvironment.Test,ProviderCapability.CalendarRead,"Review calendar candidates.",Today.AddDays(30),"Local consent profile.");
 [Fact]public void Required_fields_and_capabilities_are_validated(){var r=ProviderConsentService.Validate(Draft()with{ProfileName=null,Owner=null,Capabilities=ProviderCapability.None},Today);Assert.False(r.IsValid);Assert.NotEmpty(r.ForField("consent-name"));Assert.NotEmpty(r.ForField("consent-owner"));Assert.NotEmpty(r.ForField("consent-capabilities"));}
 [Fact]public void Past_expiry_is_rejected(){var r=ProviderConsentService.Validate(Draft()with{ExpiresOn=Today.AddDays(-1)},Today);Assert.Equal("expiry",Assert.Single(r.ForField("consent-expiry")).Code);}
 [Fact]public void Secret_like_text_is_rejected(){var r=ProviderConsentService.Validate(Draft()with{Notes="token=private"},Today);Assert.Equal("secret-like-value",Assert.Single(r.ForField("consent-notes")).Code);}
 [Fact]public void Approval_is_explicit_but_access_remains_disabled(){var r=ProviderConsentService.Create(Draft(),Today,Now);var x=ProviderConsentService.SetState(r,ProviderConsentState.Approved,Today,Now.AddMinutes(1));Assert.Equal(ProviderConsentState.Approved,x.State);Assert.False(ProviderConsentService.ProviderAccessEnabled(x));}
 [Fact]public void Expiry_is_deterministic(){var r=ProviderConsentService.Create(Draft()with{ExpiresOn=Today},Today,Now);var x=ProviderConsentService.RefreshExpiry(r,Today.AddDays(1));Assert.Equal(ProviderConsentState.Expired,x.State);}
 [Fact]public void Missing_repository_is_empty_without_file(){using Temp t=new();string p=Path.Combine(t.Path,"c.json");var r=new ProviderConsentRepository(p,today:()=>Today).LoadResult();Assert.Empty(r.Value);Assert.False(File.Exists(p));}
 [Fact]public void Repository_is_versioned(){using Temp t=new();string p=Path.Combine(t.Path,"c.json");var repo=new ProviderConsentRepository(p,today:()=>Today);repo.Save([ProviderConsentService.Create(Draft(),Today,Now)]);using var j=JsonDocument.Parse(File.ReadAllText(p));Assert.Equal("provider-consent-profiles",j.RootElement.GetProperty("storeId").GetString());}
 [Fact]public void Unsafe_record_does_not_overwrite(){using Temp t=new();string p=Path.Combine(t.Path,"c.json");var repo=new ProviderConsentRepository(p,today:()=>Today);var v=ProviderConsentService.Create(Draft(),Today,Now);repo.Save([v]);Assert.Throws<InvalidDataException>(()=>repo.Save([v with{Purpose="secret=private"}]));Assert.Single(repo.Load());}
 sealed class Temp:IDisposable{public Temp(){Path=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"lifeos-consent-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(Path);}public string Path{get;}public void Dispose(){if(Directory.Exists(Path))Directory.Delete(Path,true);}}
}
