using System.Text.Json; using LifeOS.Core.ConfigurationReadiness; using LifeOS.Shared.ConfigurationReadiness; using LifeOS.Shared.Storage; using Xunit;
namespace LifeOS.Core.Tests;
public sealed class Groups193To196ConfigurationReadinessTests
{
 static readonly DateTimeOffset Now=new(2026,8,18,1,2,3,TimeSpan.Zero); static ConfigurationReadinessDraft Draft()=>new("Sync provider",ConfigurationEnvironment.Test,"Product owner","LIFEOS_PROVIDER_TOKEN","Reference only.");
 [Fact]public void Required_fields_are_validated(){var r=ConfigurationReadinessService.Validate(Draft() with{Capability=null,Owner=null,Environment=(ConfigurationEnvironment)99});Assert.False(r.IsValid);Assert.NotEmpty(r.ForField("config-capability"));Assert.NotEmpty(r.ForField("config-owner"));Assert.NotEmpty(r.ForField("config-environment"));}
 [Fact]public void Reference_must_be_name_not_value(){var r=ConfigurationReadinessService.Validate(Draft() with{SecretReferenceName="secret-value"});Assert.Equal("reference-name",Assert.Single(r.ForField("config-secret-reference")).Code);}
 [Fact]public void Secret_like_notes_are_rejected(){var r=ConfigurationReadinessService.Validate(Draft() with{Notes="token=private-value"});Assert.Equal("secret-like-value",Assert.Single(r.ForField("config-notes")).Code);}
 [Fact]public void Create_tracks_reference_without_resolving_it(){var r=ConfigurationReadinessService.Create(Draft(),Now);Assert.Equal(ConfigurationReadinessState.ReadyForConfiguredTest,r.State);Assert.Equal("LIFEOS_PROVIDER_TOKEN",r.SecretReferenceName);}
 [Fact]public void Missing_repository_is_empty_without_file(){using Temp t=new();string p=Path.Combine(t.Path,"c.json");var repo=new ConfigurationReadinessRepository(p);var r=repo.LoadResult();Assert.Empty(r.Value);Assert.False(File.Exists(p));}
 [Fact]public void Repository_is_versioned(){using Temp t=new();string p=Path.Combine(t.Path,"c.json");var repo=new ConfigurationReadinessRepository(p);repo.Save([ConfigurationReadinessService.Create(Draft(),Now)]);using var j=JsonDocument.Parse(File.ReadAllText(p));Assert.Equal("configuration-readiness",j.RootElement.GetProperty("storeId").GetString());Assert.Single(repo.Load());}
 [Fact]public void Unsafe_record_does_not_overwrite(){using Temp t=new();string p=Path.Combine(t.Path,"c.json");var repo=new ConfigurationReadinessRepository(p);var v=ConfigurationReadinessService.Create(Draft(),Now);repo.Save([v]);Assert.Throws<InvalidDataException>(()=>repo.Save([v with{Notes="password=hunter2"}]));Assert.Equal("Reference only.",Assert.Single(repo.Load()).Notes);}
 [Fact]public void Trash_restore_refuses_overwrite(){using Temp t=new();string p=Path.Combine(t.Path,"c.json");var repo=new ConfigurationReadinessRepository(p);repo.Save([ConfigurationReadinessService.Create(Draft(),Now)]);var x=repo.MoveToTrash();repo.RestoreTrash(x.Id);Assert.Throws<InvalidOperationException>(()=>repo.RestoreTrash(x.Id));}
 sealed class Temp:IDisposable{public Temp(){Path=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"lifeos-config-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(Path);}public string Path{get;}public void Dispose(){if(Directory.Exists(Path))Directory.Delete(Path,true);}}
}
